### ISSUE TITLE
Add support for base URL

### ISSUE THREAD

**Issue by tijme** [franciscop/pagex#1]
The library is not working when working in a subdirectory (e.g. http://localhost/test).

I tried using the base tag `<base href="/test/" />`, but it didn't work.

This is the code I used:

``` html
<!DOCTYPE html>
<html>
    <head>
        <title>Test</title>
        <base href="/test/" />
    </head>
    <body>
        <script src="pagex.min.js"></script>
        <script>

            pagex('/hi', function() {
                alert('hi');
            });

        </script>
    </body>
</html>
```

And this is the URL I tried:
`http://localhost/test/hi`

**Comment by franciscop** [comment]
While parsing the html is not within the goals for this library, I could easily add a hook so you can just parse it (this is not yet working):

``` js
pagex.base = '/test';

pagex('/hi', function() {
  alert('hi');
});
```

Or, just parse it automatically:

``` js
var base = document.getElementsByTagName('base')[0];
if (base) pagex.base = base.getAttribute('href');
// or with jquery:
pagex.base = $('base').attr('href');

pagex('/hi', function() {
  alert('hi');
});
```

**Would that work for you?** I thought about making it before but also that it'd be overkill and I prefer a lot explicit routes as I think they are easier for future programmers, but I can see the value or different preference.

**Comment by franciscop** [comment]
This also looks like a great solution:

``` js
// /test/*
pagex('/test', function(){
  alert('hi all');

  // /test/one
  pagex('/one', function(){
    alert('hi 1');
  });

  // /test/two
  pagex('/two', function(){
    alert('hi 2');
  });
});
```

But has big problems with other kind of routes:

``` js
pagex('/test/:id/frag?', function(){

  // ??
  pagex('/weird', function(){
    alert('hi');
  });
});
```

If we keep a separated `pagex.base` that can only be a string with a explicit url format (as in your example) then we get no problems at all.

**Comment by franciscop** [comment]
Perfect, with commit https://github.com/franciscop/pagex/commit/0497b4f83036c131f095e5e76c6eef7e293c7588 this should work:

``` html
<!DOCTYPE html>
<html>
    <head>
        <title>Test</title>
        <base href="/test/" />
    </head>
    <body>
        <script src="pagex.min.js"></script>
        <script>
            var base = document.getElementsByTagName('base')[0];
            if (base) pagex.base = base.getAttribute('href');

            pagex('/hi', function() {
                alert('hi');
            });
        </script>
    </body>
</html>
```

Please report any issue you find

**Comment by tijme** [comment]
That's a great solution. Thanks!

**Comment by franciscop** [comment]
Awesome :+1:
